name: Deploy to Timeweb Kubernetes

on:
  push:
    branches: [ "main" ]  # Триггер на пуш в main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Configure Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config
          kubectl cluster-info

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yaml -n default
          kubectl apply -f k8s/service.yaml -n default
